version: '3.8'

services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: monitor

  frontend:
    build: ./dashboard
    container_name: frontend
    ports:
      - "3000:80"

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitor
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis